name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js v10
        uses: actions/setup-node@v2
        with:
          node-version: '10.21.0'

      - name: Use Build action
        uses: ./.github/actions/build
