name: Publish

on:
  push:
    tags:
      - '*-rc*'

jobs:

  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js v10
        uses: actions/setup-node@v2
        with:
          node-version: '10.21.0'
          registry-url: 'https://registry.npmjs.org'

      - name: Use Build action
        uses: ./.github/actions/build

      - name: Publish
        run: npm publish --tag next
        env:
          NODE_AUTH_TOKEN: ${{ secrets.TIERRATELEMATICS_NPM }}
